language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - travis_retry composer self-update && composer install --dev --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

notifications:
  irc: "irc.freenode.org#ouarz"
  email:
    recipients:
      - dev-team@ouarz.net
    on_success: change
    on_failure: change

after_script:
- php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
